<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CSB55GA" name="Default test" tests="19" failures="2" timestamp="15 Aug 2019 12:51:26 GMT" time="45.562" errors="0">
  <testcase name="Verify_Url" time="0.033" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="verifyApplicationTitle" time="0.012" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="verify_Title" time="0.097" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="loginsesion" time="0.02" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="Check_PlaceHolder_Username" time="0.033" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="Check_PlaceHolder_Password" time="0.028" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="check_Button_color" time="0.087" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="check_Links" time="0.054" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="blank_username_password" time="0.311" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="invalidusername_password" time="4.411" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="validUsername_Password" time="2.266" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="Verify_Url_DashBoard" time="0.016" classname="TestNgDemo.TestNgMaven.Login_TestCase">
    <failure type="java.lang.AssertionError" message="expected [file:///C:/Users/comp/Desktop/Selenium%20Software/Offline%20Website/index.html] but found [file:///C:/Users/comp/Desktop/Selenium%20Software/Offline%20Website/pages/examples/dashboard.html]">
      <![CDATA[java.lang.AssertionError: expected [file:///C:/Users/comp/Desktop/Selenium%20Software/Offline%20Website/index.html] but found [file:///C:/Users/comp/Desktop/Selenium%20Software/Offline%20Website/pages/examples/dashboard.html]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at TestNgDemo.TestNgMaven.Login_TestCase.Verify_Url_DashBoard(Login_TestCase.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Verify_Url_DashBoard -->
  <testcase name="verifyApplicationTitle_DashBoard" time="0.026" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="heading_Dashboard" time="2.042" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="click_OnUser" time="5.163" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="getTableData" time="7.847" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="Click_On_AddUser_Btn" time="2.169" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="Fill_Form" time="14.36" classname="TestNgDemo.TestNgMaven.Login_TestCase"/>
  <testcase name="logOutBtn" time="6.114" classname="TestNgDemo.TestNgMaven.Login_TestCase">
    <failure type="org.openqa.selenium.NoSuchElementException" message="Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//p[contains(text(),&amp;apos;Logout successfully done&amp;apos;)]&amp;quot;}
Command duration or timeout: 5.39 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &amp;apos;2.53.0&amp;apos;, revision: &amp;apos;35ae25b1534ae328c771e0856c93e187490ca824&amp;apos;, time: &amp;apos;2016-03-15 10:43:46&amp;apos;
System info: host: &amp;apos;DESKTOP-CSB55GA&amp;apos;, ip: &amp;apos;192.168.1.10&amp;apos;, os.name: &amp;apos;Windows 8.1&amp;apos;, os.arch: &amp;apos;x86&amp;apos;, os.version: &amp;apos;6.3&amp;apos;, java.version: &amp;apos;1.8.0_45&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 27074d90-685f-41ca-9690-8ca522ef9463
*** Element info: {Using=xpath, value=//p[contains(text(),&amp;apos;Logout successfully done&amp;apos;)]}">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//p[contains(text(),'Logout successfully done')]"}
Command duration or timeout: 5.39 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'DESKTOP-CSB55GA', ip: '192.168.1.10', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 27074d90-685f-41ca-9690-8ca522ef9463
*** Element info: {Using=xpath, value=//p[contains(text(),'Logout successfully done')]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at TestNgDemo.TestNgMaven.Login_TestCase.logOutBtn(Login_TestCase.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//p[contains(text(),'Logout successfully done')]"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'DESKTOP-CSB55GA', ip: '192.168.1.10', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///C:/Users/comp/AppData/Local/Temp/anonymous7771037330437934977webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///C:/Users/comp/AppData/Local/Temp/anonymous7771037330437934977webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:625)
]]>
    </failure>
  </testcase> <!-- logOutBtn -->
</testsuite> <!-- Default test -->
